#ansible-playbook ./playbooks/password-change.yml --user someuser --ask-become-pass -i ./inventory/hosts
- name: password change
  hosts: "*"
  become: true
  vars_prompt:
  - name: new_password
    prompt: "Enter new password"
  tasks:
  - name: change user's password
    user:
      name: "{{ ansible_user }}"
      update_password: always
      password: "{{ new_password|password_hash('sha512') }}"

